services:
  # Avvio il container proxy server di Nginx
  proxy_server:
    container_name: proxy_server
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app

  # Avvio il container NodeJs con il server ExpressJs
  app:
    container_name: app-node
    build: ./app
    restart: always
    depends_on:
      - db

  # Avvio il container MySQL
  db:
    container_name: db
    restart: always
    image: postgres:16.3-alpine3.20
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports: 
      - 5432:5432

    healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5

volumes:
  db-data: